# Quick Start Guide

WARNING: **This is a develment branch for testing purpouse only. !!!Not tested/Not released/Not supported!!!**

## Supported CompuLab Machines

* `mcm-imx8m-mini`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-zeus -m imx-5.4.24-2.1.0.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b rel_imx_5.4.24_2.1.0-dev https://github.com/compulab-yokneam/meta-bsp-imx8mm.git sources/meta-bsp-imx8mm/

# Set a desire machine
* `mcm-imx8m-mini`
[source,console]
COMPULAB_MACHINE=mcm-imx8m-mini

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-imx/tree/README?h=zeus-5.4.3-2.0.0[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

## imx8mm
This example shows how to build an NXP supported image for the `${COMPULAB_MACHINE}`
[source,console]
MACHINE=${COMPULAB_MACHINE} source sources/meta-bsp-imx8mm/tools/setup-imx8mm-env -b build-xwayland
bitbake -k fsl-image-qt5-validation-imx

## Pre-built image
* https://drive.google.com/drive/folders/1YBVkbQVl8pub3IbBey1JLv_m3V0frV1r[XWayland Qt5 Image]
