SRC_URI:append = " \
	file://0000-iot-gate-imx8-Add-device-support.patch \
	file://0001-iio-adc-Add-Maxim-MAX11108-driver.patch \
	file://0002-firmware-Add-the-brcm-firmware-to-the-kernel-tree.patch \
	file://0003-rtc-abx80x-Enable-SQW-output.patch \
	file://0004-rtc-abx80x-Enable-XT-digital-calibration.patch \
	file://0005-rtc-abx80x-Improve-sqw-generation.patch \
	file://0006-rtc-abx80x-Improve-xt_calibration.patch \
	file://0007-rtc-abx80x-Add-sqw-binding-doc.patch \
	file://0008-rtc-abx80x-Add-xt_calibration-binding-doc.patch \
	file://0009-rtc-abx80x-Disable-bus-when-powered-from-battery.patch \
	file://0010-serial-imx-allow-passing-rs485-options.patch \
	file://defconfig \
"
