SRC_URI_append_ucm-imx8m-mini = " \
	file://0000-ucm-imx8m-mini-add-basic-support.patch \
	file://0001-ov5640_mipi_v2-gpio_set_value_cansleep.patch \
	file://0002-ucm-imx8m-mini-dts-remove-phy-supply.patch \
	file://0003-ucm-imx8m-mini-dts-Enable-onboard-LED.patch \
	file://0004-ucm-imx8m-mini-dts-Fix-CSI-reset-GPIO.patch \
	file://0005-ucm-imx8m-mini-dts-Fix-SD2-properties.patch \
	file://0006-sb-ucm-imx8m-rev2.0-dts-Enable-I2C-GPIO-expander.patch \
	file://0007-sb-ucm-imx8m-rev2.0-dts-Enable-PCIe.patch \
	file://0008-ucm-imx8m-mini-dts-Enable-onboard-EEPROM.patch \
	file://0009-sb-ucm-imx8m-rev2.0-dts-Enable-baseboard-EEPROM.patch \
	file://0010-ucm-imx8m-mini-Enable-Sterling-LWB5-Wi-Fi-over-SDIO.patch \
	file://0011-ucm-imx8m-mini-Enable-touchscreen.patch \
	file://0012-ucm-imx8m-mini-dts-Add-thermal-test-device-tree.patch \
	file://0013-sn65dsi83-Add-ti-sn65dsi83-dsi-to-lvds-bridge-driver.patch \
	file://0014-ucm-imx8m-mini-Enable-lvds-in-device-tree.patch \
	file://0015-startek-ili9881c-Add-panel-driver.patch \
	file://0016-ucm-imx8m-mini-Enable-mipi-dsi-panel-in-device-tree.patch \
	file://0017-ucm-imx8m-mini-defconfig-Enable-startek-ili9881c.patch \
	file://0018-ucm-imx8m-mini-defconfig-Update-defconfig.patch \
	file://0019-startek-ili9881c-Change-pixel-clock-tom-85M.patch \
	file://defconfig \
"
