SRC_URI_append_ucm-imx8m-mini = " \
	file://0000-ucm-imx8m-mini-add-basic-support.patch \
	file://0001-ov5640_mipi_v2-gpio-can-sleep.patch \
	file://0002-panel-ilitek-ili9881c-add-ilitek-panel-support.patch \
	file://0003-ucm-imx8m-mini-config-enable-ilitek-panel.patch \
	file://0004-ucm-imx8m-mini-dsi-dts-add-mipi-device-tree.patch \
	file://0005-panel-ilitek-ili9881c-update-0.patch \
	file://0006-ucm-imx8m-mini-dts-remove-phy-supply.patch \
	file://0007-sn65dsi83-add-dsi2lvds-bridge.patch \
	file://0008-ucm-imx8m-mini-lvds-dts-add-device-tree-file.patch \
	file://defconfig \
"
