#!/bin/bash

CONF=/etc/fw_env.config

force_rw() {
for _d in $(awk '(/^\/dev\//)&&($0=$1)' ${CONF});do
_d=$(basename $_d)
if [[ -f /sys/class/block/${_d}/force_ro ]];then
	if [[ ${1} -eq 1 ]];then
		export eval ${_d}=$(cat /sys/class/block/${_d}/force_ro)
		echo 0 > /sys/class/block/${_d}/force_ro
	else
		echo ${!_d} > /sys/class/block/${_d}/force_ro
	fi
fi
done
}

force_rw 1

fw_setenv $@

force_rw 0
