#!/bin/bash -e
MACHINE=${MACHINE:-mcm-imx8m-mini}
DISTRO=${DISTRO:-fsl-imx-xwayland}
EULA=1

. imx-setup-release.sh $@

declare -a ENVIRONMENT=('../sources/meta-bsp-imx8mm/tools/setup-compulab-env
		../sources/meta-bsp-imx8mm/tools/setup-user-env')

for env in ${ENVIRONMENT[@]};do
	[ -f ${env} ] && FORCE=Yes source ${env}
done
